---
- name: Destroy netris-lab
  ansible.builtin.command:
    cmd: make destroy
    chdir: "{{ netris_lab_dir }}"
  register: _lab_destroy
  failed_when: false
  changed_when: _lab_destroy.rc == 0

- name: Stop Assisted Service pods
  ansible.builtin.command:
    cmd: podman pod rm -f assisted-installer
  register: _ai_destroy
  failed_when: false
  changed_when: _ai_destroy.rc == 0

- name: Remove dnsmasq OCP config
  ansible.builtin.file:
    path: /etc/dnsmasq.d/ocp-sno.conf
    state: absent

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
  failed_when: false
