---
- name: Full Netris lab OCP SNO + OSAC deployment
  hosts: all
  gather_facts: false
  roles:
    - lab_deploy
    - vm_resize
    - netris_configure
    - assisted_service
    - ocp_install
    - osac_install
