---
- name: Delete BareMetalHost objects
  ansible.builtin.command:
    cmd: >
      oc delete baremetalhost -n {{ snapshot_osac_namespace | default(osac_namespace) }}
      -l osac.openshift.io/host-type={{ bmaas_host_type_id }} --ignore-not-found
  environment:
    KUBECONFIG: /root/.kube/config
  changed_when: true

- name: Delete BMC credentials secret
  ansible.builtin.command:
    cmd: oc delete secret bmaas-bmc-creds -n {{ snapshot_osac_namespace | default(osac_namespace) }} --ignore-not-found
  environment:
    KUBECONFIG: /root/.kube/config
  changed_when: true
